### ISSUE TITLE
Remind plugin doesn't work properly

### ISSUE THREAD

**Issue by Muzer** [thomasleese/smartbot#11]
The whole listing reminders things simply doesn't work

    <@Muzer> SmartBot: help remind
    <SmartBot> SmartBot remind (me) <note> - Creates a new reminder using <note>
    <SmartBot> SmartBot remind (me) now - Returns all your reminders
    <SmartBot> SmartBot remind cancel - Cancels the reminder operation
    <SmartBot> SmartBot remind clear - Clears all your reminders
    <@Muzer> SmartBot: remind now
    <SmartBot> Muzer: When should I remind you?
    <@Muzer> that really doesn't work

**Comment by thomasleese** [comment]
Pull request submitted: https://github.com/ClaudeBot/hubot-remind-advanced/pull/1
