### ISSUE TITLE
Sleepyti.me style plugin

### ISSUE THREAD

**Issue by AliHawke** [thomasleese/smartbot#60]
Just play around with sleepyti.me a bit to figure out the start time, buffer, and subsequent cycles. Ideally, would be operated by "SmartBot: sleepytime" ![MRW](http://media.giphy.com/media/lc02M5TmttaTu/giphy.gif), to which SmartBot calculates and responds, e.g. "4:05 AM or 5:35 AM or 7:05 AM or 8:35 AM (ok) or 10:05 AM (decent) or 11:35 AM (optimal)" to tell users when they should wake up, if they have the flexibility to pick when.
![:3](http://media.giphy.com/media/WQgMECwmjCYZa/giphy.gif)

**Comment by thomasleese** [comment]
Just because you can put animated GIFs in, doesn't mean you should…

**Comment by AliHawke** [comment]
![but... but...](http://media.giphy.com/media/oOX5qIDkzDjeo/giphy.gif)

**Comment by thomasleese** [comment]
Fixed in a86150c016fd88da9849c8abe58e7a3cf9233521! Only took 3 months. :+1:
