### ISSUE TITLE
You better believe it!

### ISSUE THREAD

**Issue by thomasleese** [thomasleese/smartbot#61]
That’s right, you better.

**Comment by AliHawke** [comment]
![blates another bluff](http://www.reactiongifs.com/r/2013/06/I-dont-believe-you.gif)

**Comment by thomasleese** [comment]
I opened this only fifteen days ago, but I have literally forgotten what this plugin was meant to be. Perils of trying to be funny I suppose…

**Comment by AliHawke** [comment]
![facepalm](http://media.giphy.com/media/6yRVg0HWzgS88/giphy.gif) It was to have SmartBot randomly say to me "You'd better believe it!".

**Comment by thomasleese** [comment]
![Thanks!](http://media.giphy.com/media/hrBSJ2So6iTo4/giphy.gif)

**Comment by AliHawke** [comment]
![np](http://media.giphy.com/media/nugyKi9xAyzxC/giphy.gif)

**Comment by thomasleese** [comment]
Fixed in 6b3b6c77f291c2d7d8e21905326b9717e067ab53!
