### ISSUE TITLE
Jokel 'joke' feature alteration

### ISSUE THREAD

**Issue by AliHawke** [thomasleese/smartbot#62]
Given that all the infamously terrible jokel content tends to be of the question and answer joke format, I think it would be fun if there's a 60 second gap between SmartBot asking the question and saying the punchline, so that people have time to guess what the awful and offensive joke will be, just like real life.
![airplane](http://media.giphy.com/media/4O7CPRT2NAZxu/giphy.gif)

**Comment by thomasleese** [comment]
Fixed in f2691f1a848cdacc25f696f1469e3f829e0ccd1d, although I took the decision to set the delay to 45 seconds.
